import Head from 'next/head'
import styles from '../styles/Home.module.css'
import useSWR from "swr";
import { useState } from 'react';
import Link from 'next/link';


const fetcher = (...args) => fetch(...args).then((res) => res.json());
export default function Home() {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
      const [posts, setPosts] = useState('');
  const { data, error, isLoading } = useSWR(`${process.env.NEXT_PUBLIC_API_URL}/posts`,
        fetcher
    );

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>

   function handleChange(e) {
    setTitle(e.target.value);
  }

   function handleChange1(e) {
    setDescription(e.target.value);
  }

  async function handleSubmit() {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/users/1/posts/`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        title: title,
        description: description
      })
    })
    const json = await res.json();
    setPosts([...posts, json])
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && data.map((item) => (
          <div key={item.id}>
          <h1>{item.title}</h1>
          <p>{item.description} </p>
          <Link href={`/post/${item.id}`} >read more</Link>
          </div>


      ))}
      <input type='text' value={title} onChange={handleChange} ></input>
        <textarea value={description} onChange={handleChange1} className="border-2" ></textarea>
            <button onClick={handleSubmit} className="bg-green-500 p-3 text-white">Submit</button>
          </div>
  )
}
